### PR TITLE
Use AsyncLocal hold HttpRequestMessage.

### LINKED ISSUE #64: Change CallContext to AsyncLocal
Refactoring `HttpRequestMessageProvider`, change CallContext to AsyncLocal.

```
System.Security.SecurityException : Type System.Runtime.Remoting.ObjRef and the types derived from it (such as System.Runtime.Remoting.ObjRef) are not permitted to be deserialized at this security level.

Server stack trace: 
   at System.Runtime.Serialization.FormatterServices.CheckTypeSecurity(Type t, TypeFilterLevel securityLevel)
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.CheckSecurity(ParseRecord pr)
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseObject(ParseRecord pr)
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Parse(ParseRecord pr)
   at System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadObjectWithMapTyped(BinaryObjectWithMapTyped record)
   at System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadObjectWithMapTyped(BinaryHeaderEnum binaryHeaderEnum)
   at System.Runtime.Serialization.Formatters.Binary.__BinaryParser.Run()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(HeaderHandler handler, __BinaryParser serParser, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, HeaderHandler handler, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Runtime.Remoting.Channels.CoreChannel.DeserializeBinaryRequestMessage(String objectUri, Stream inputStream, Boolean bStrictBinding, TypeFilterLevel securityLevel)
   at System.Runtime.Remoting.Channels.BinaryServerFormatterSink.ProcessMessage(IServerChannelSinkStack sinkStack, IMessage requestMsg, ITransportHeaders requestHeaders, Stream requestStream, IMessage& responseMsg, ITransportHeaders& responseHeaders, Stream& responseStream)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at ......
```

### PR DESCRIPTION
**Pull request by pengweiqhca**
Fix #64.

### CODE REVIEW

**Comment by tillig** [comment]
I don't really want this to be a thing where we maintain two different configurable paths for this. If it's going to be `AsyncLocal`, it just needs to be `AsyncLocal`. I think that should be available in all clients since we support .NET 4.7.2 minimum here now. Can you remove the switch and just default it to `AsyncLocal`?

**Comment by pengweiqhca** [comment]
Add switch, no need to consider compatibility issues and will not change the existing behavior.

**Comment by tillig** [comment]
I understand the idea, but you're not the one who's going to have to own, maintain, and support it long term. Making it easy to support is kind of important since there aren't actually that many people dedicated here.

If we're going `AsyncLocal`, let's do it and we can release a minor version to indicate it's a new feature rather than a backwards compatible bug fix.

If we get complaints, we can roll it back or fix forward then.

**Comment by pengweiqhca** [comment]
Switch removed.

**Comment by tillig** [comment]
Looking at the way [ASP.NET Core uses `AsyncLocal` in `HttpContextAccessor`](https://github.com/dotnet/aspnetcore/blob/a450cb69b5e4549f5515cdb057a68771f56cefd7/src/Http/Http/src/HttpContextAccessor.cs) it appears they use some object indirection - a holder for the context instead of storing the context itself - to ensure changing and updating happens across all execution contexts.

Should we do [something like that here](https://github.com/dotnet/aspnetcore/blob/a450cb69b5e4549f5515cdb057a68771f56cefd7/src/Http/Http/src/HttpContextAccessor.cs#L35)?

**Comment by pengweiqhca** [comment]
`HttpContextAccessor` look like a new feature, but I just want to fix the "bug" at the moment.

**Comment by tillig** [comment]
I'm not asking you to use `HttpContrxtAccessor`, I'm suggesting that you may need that "holder" object sort of thing here - the holder contains the message, the `AsyncLocal` contains the holder.

**Comment by pengweiqhca** [comment]
Modify `static HttpRequestMessageProvider` to `interface IHttpRequestMessageAccessor`?

**Comment by tillig** [comment]
No. Go look at the code for `HttpContextAccessor` that I linked. Pretend the `HttpRequestMessage` here is the `HttpContext` there. Look at what their `AsyncLocal` stores. You'll see it does not directly store `HttpContext`. It stores a holder object. The holder object stores `HttpContext`. I'm saying you need the holder object in here, and the holder should store the request message.

If this still doesn't make sense you'll have to wait a while for one of us to do the change. I'm heading into some desperately needed time off so basically all I have is my phone. I won't be able to take care of it for a while

**Review by tillig — APPROVED** [review]
Looks great, thanks!

**Comment by tillig** [comment]
I'll cut a release as soon as I can. It should end up being 6.1.0.

**Comment by tillig** [comment]
Published.

**Pull request merged**
