### PR TITLE
chore: update to stable v6

### PR DESCRIPTION
**Pull request by alsami**
Update to stable v6

### CODE REVIEW

**Comment by alsami** [comment]
@tillig @alistairjevans one more, let me do the easy work 😄

**Review by alistairjevans — APPROVED** [review]
🍗

**Comment by izvictor** [comment]
Hello,
Are you planning to release a new version of Autofac.WebApi compatible with 6.0 of Autofac in near future?
Thanks

**Comment by alsami** [comment]
> Hello,
> Are you planning to release a new version of Autofac.WebApi compatible with 6.0 of Autofac in near future?
> Thanks

It's gonna be released soon, shouldn't take too long now.

**Comment by alistairjevans** [comment]
[Ask and ye shall receive](https://github.com/autofac/Autofac.WebApi/releases/tag/v6.0.0) (sometimes, maybe).

**Pull request merged**
