### PR TITLE
Compatibility with v6; CLS Compliant = false + version bump

### PR DESCRIPTION
**Pull request by alistairjevans**

### CODE REVIEW

**Comment by tillig** [comment]
If there were no code changes other than the CLS compliance thing, could we leave the Autofac dependency versions at 5 and just change compatibility to `[5.0.0,7.0.0)`? Or is it something to do with source vs binary compatibility?

**Comment by alistairjevans** [comment]
The two versions should indeed be compatible; would that still be a major version change of the package?

**Comment by alistairjevans** [comment]
Worth noting that if someone has `CLSCompliant(true)` in their project, then upgrading their version of this package will result in warnings (or errors if they have the setting on). Is that considered a breaking change?

**Comment by tillig** [comment]
Probably a major version change on this WebApi package for the CLSCompliant update but we can keep the minimum version compatibility to Autofac 5 and just extend the upper limit.

**Comment by alistairjevans** [comment]
Brought the nuspec bottom range back down to 5. Major version up to 6.

**Review by tillig — APPROVED** [review]
🎖️

**Pull request merged**
